shell = "zsh"

# [plugins]

[plugins.compinit]
inline = 'autoload -U compinit && compinit && autoload -Uz colors && colors'

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.starship]
inline = ' eval "$(starship completions zsh)" && eval "$(starship init zsh)"'

[plugins.zabrze]
inline = 'eval "$(zabrze init --bind-keys)"'

[plugins.gh]
inline = 'eval "$(gh completion -s zsh)"'

# [plugins.zsh-abbr]
# github = "olets/zsh-abbr"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# [plugins.powerlevel10k]
# github = "romkatv/powerlevel10k"

[plugins.fzf]
github = "junegunn/fzf"
use = ["shell/*.zsh"]

# [plugins.fzf-tab]
# github = 'Aloxaf/fzf-tab'
# use = ['fzf-tab.zsh']

[plugins.syntax-highlight]
github = 'z-shell/F-Sy-H'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions" 

[plugins.z]
github = "rupa/z" 

[plugins.mise-completion]
inline = 'eval "$(mise completion zsh)"'

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-completion]
# https://github.com/zsh-users/zsh-completions/tree/master/src
github = "zsh-users/zsh-completions"
use = ["src/_cmake", "src/_npm", "src/_openssl", "src/_setup.py", "src/_uuidd", "src/_uuidgen"]